[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"

[dependencies.tokio]
version = "1.48.0"
features = ["rt", "rt-multi-thread", "io-util", "time", "net", "macros"]
